[package]
name = "lapiz_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
lapiz_runtime_derive.workspace = true
downcast-rs.workspace = true
winit.workspace = true
iced_runtime.workspace = true
iced_core.workspace = true
iced_futures.workspace = true
iced_winit.workspace = true
iced_wgpu.workspace = true
wgpu.workspace = true
log.workspace = true
lapiz_utils.workspace = true
iced_graphics.workspace = true
rustc-hash.workspace = true
parking_lot.workspace = true
futures.workspace = true
smol.workspace = true
parse-display.workspace = true
raw-window-handle.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"] }
