[package]
name = "lapiz_bucket_tool"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bevy_math.workspace = true
bytemuck.workspace = true
lapiz_anti_aliasing.workspace = true
lapiz_canvas.workspace = true
lapiz_color.workspace = true
lapiz_i18n.workspace = true
lapiz_image.workspace = true
lapiz_input.workspace = true
lapiz_render.workspace = true
lapiz_runtime.workspace = true
lapiz_tools.workspace = true
lapiz_utils.workspace = true
lapiz_widgets.workspace = true
encase.workspace = true
glam.workspace = true
iced_core.workspace = true
iced_runtime.workspace = true
iced_futures.workspace = true
iced_wgpu.workspace = true
iced_widget.workspace = true
indexmap.workspace = true
tracing.workspace = true
wesl.workspace = true
wgpu.workspace = true

rust-embed.workspace = true

[build-dependencies]
lapiz_image.workspace = true
lapiz_render.workspace = true
wesl.workspace = true
