[workspace]
members = [
    "crates/lapiz_abr",
    "crates/lapiz_abr_bridge",
    "crates/lapiz_abr_derive",
    "crates/lapiz_actions",
    "crates/lapiz_anti_aliasing",
    "crates/lapiz_app",
    "crates/lapiz_assets",
    "crates/lapiz_brush",
    "crates/lapiz_bucket_tool",
    "crates/lapiz_canvas",
    "crates/lapiz_color",
    "crates/lapiz_color_selector",
    "crates/lapiz_dock",
    "crates/lapiz_filter",
    "crates/lapiz_i18n",
    "crates/lapiz_image",
    "crates/lapiz_input",
    "crates/lapiz_lazuli",
    "crates/lapiz_math",
    "crates/lapiz_render",
    "crates/lapiz_runtime",
    "crates/lapiz_runtime_derive",
    "crates/lapiz_selection_tool",
    "crates/lapiz_transform_tool",
    "crates/lapiz_shader_graph",
    "crates/lapiz_shader_graph_derive",
    "crates/lapiz_tools",
    "crates/lapiz_undo",
    "crates/lapiz_utils",
    "crates/lapiz_utils_derive",
    "crates/lapiz_widgets",
]
resolver = "3"
default-members = ["crates/lapiz_app"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.package]
publish = false
edition = "2024"
rust-version = "1.96.0"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[workspace.dependencies]
lapiz_abr = { version = "0.1.0", path = "crates/lapiz_abr" }
lapiz_abr_bridge = { version = "0.1.0", path = "crates/lapiz_abr_bridge" }
lapiz_abr_derive = { version = "0.1.0", path = "crates/lapiz_abr_derive" }
lapiz_actions = { version = "0.1.0", path = "crates/lapiz_actions" }
lapiz_anti_aliasing = { version = "0.1.0", path = "crates/lapiz_anti_aliasing" }
lapiz_assets = { version = "0.1.0", path = "crates/lapiz_assets" }
lapiz_brush = { version = "0.1.0", path = "crates/lapiz_brush" }
lapiz_bucket_tool = { version = "0.1.0", path = "crates/lapiz_bucket_tool" }
lapiz_canvas = { version = "0.1.0", path = "crates/lapiz_canvas" }
lapiz_color = { version = "0.1.0", path = "crates/lapiz_color" }
lapiz_color_selector = { version = "0.1.0", path = "crates/lapiz_color_selector" }
lapiz_dock = { version = "0.1.0", path = "crates/lapiz_dock" }
lapiz_filter = { version = "0.1.0", path = "crates/lapiz_filter" }
lapiz_i18n = { version = "0.1.0", path = "crates/lapiz_i18n" }
lapiz_image = { version = "0.1.0", path = "crates/lapiz_image" }
lapiz_input = { version = "0.1.0", path = "crates/lapiz_input" }
lapiz_lazuli = { version = "0.1.0", path = "crates/lapiz_lazuli" }
lapiz_math = { version = "0.1.0", path = "crates/lapiz_math" }
lapiz_render = { version = "0.1.0", path = "crates/lapiz_render" }
lapiz_runtime = { version = "0.1.0", path = "crates/lapiz_runtime" }
lapiz_runtime_derive = { version = "0.1.0", path = "crates/lapiz_runtime_derive" }
lapiz_shader_graph = { version = "0.1.0", path = "crates/lapiz_shader_graph" }
lapiz_shader_graph_derive = { version = "0.1.0", path = "crates/lapiz_shader_graph_derive" }
lapiz_selection_tool = { version = "0.1.0", path = "crates/lapiz_selection_tool" }
lapiz_transform_tool = { version = "0.1.0", path = "crates/lapiz_transform_tool" }
lapiz_tools = { version = "0.1.0", path = "crates/lapiz_tools" }
lapiz_undo = { version = "0.1.0", path = "crates/lapiz_undo" }
lapiz_utils = { version = "0.1.0", path = "crates/lapiz_utils" }
lapiz_utils_derive = { version = "0.1.0", path = "crates/lapiz_utils_derive" }
lapiz_widgets = { version = "0.1.0", path = "crates/lapiz_widgets" }

anyhow = "1"
arc-swap = "1"
atomicow = "1"
bevy_color = "0.18"
bevy_math = { version = "0.18", git = "https://github.com/443eb9/bevy.git", branch = "release-0.18.1", features = [
    "serialize",
    "std",
    "curve",
    "encase",
] }
bitflags = "2"
bytemuck = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
dashmap = "6"
downcast-rs = "2"
dyn-clone = "1"
encase = "0.12"
env_logger = "0.11"
flate2 = "1"
fluent-bundle = "0.16"
fluent-syntax = "0.12"
fs_extra = "1"
futures = "0.3"
glam = { version = "0.30", features = ["encase", "serde", "bytemuck"] }
half = "2"
i18n-embed = { version = "0.16", features = ["fluent-system", "desktop-requester"] }
iced = { version = "0.15.0-dev", default-features = false, features = [
    "wgpu",
    "crisp",
    "web-colors",
    "thread-pool",
    "linux-theme-detection",
    "x11",
    "wayland",
    "debug",
    "canvas",
    "selector",
    "smol",
] }
iced_core = "0.15.0-dev"
iced_futures = { version = "0.15.0-dev", features = ["smol"] }
iced_graphics = { version = "0.15.0-dev", features = ["geometry"] }
iced_runtime = "0.15.0-dev"
iced_wgpu = { version = "0.15.0-dev", features = ["geometry", "svg"] }
iced_widget = { version = "0.15.0-dev", features = ["wgpu", "canvas", "svg", "advanced"] }
iced_winit = "0.15.0-dev"
image = "0.25"
indexmap = { version = "2", features = ["serde"] }
log = "0.4"
lyon = "1"
md5 = "0.8"
moxcms = "0.8"
num-traits = "0.2"
num_enum = "0.7"
palette = "0.7"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
paste = "1"
parse-display = "0.11"
path-clean = "1"
proc-macro2 = "1"
proc-macro-crate = "3.5"
quote = "1"
raw-window-handle = { version = "0.6", features = ["std"] }
rayon = "1"
rfd = "0.17"
rmp = "0.8"
rmp-serde = "1"
ringbuffer = "0.16"
rusqlite = { version = "0.40", features = ["bundled-full"] }
rust-embed = "8"
rustc-hash = "1"
schemars = { version = "1", features = ["uuid1"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
smallvec = "1"
smol = "2"
taffy = { version = "0.10", default-features = false, features = ["std", "taffy_tree", "flexbox"] }
syn = "2"
thiserror = "2"
toml = "1"
tracing = "0.1"
unic-langid = "0.9"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "v5", "serde"] }
variadics_please = "2"
wesl = { version = "0.4", features = ["package", "naga-ext"] }
wesl-quote = "0.4"
wgpu = "29"
windows = "0.62"
winit = "0.31.0-beta.3"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
zip = "8"

[patch.crates-io]
iced = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_beacon = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_core = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_debug = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_devtools = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_futures = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_graphics = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_program = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_renderer = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_runtime = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_selector = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_wgpu = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_widget = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
iced_winit = { git = "https://github.com/443eb9/iced.git", rev = "c014126fc1148e9020fa60d3a528e5731cc6df17" }
