version = 1

# Contributor identities and history are maintained by GitHub:
# https://github.com/lapiz-rs/lapiz/graphs/contributors

[[annotations]]
path = [
    ".cargo/**",
    ".github/**",
    "assets/**",
    "android/app/**",
    "android/build.gradle.kts",
    "android/settings.gradle.kts",
    "android/toolchain.properties",
    "android/gradle/gradle-daemon-jvm.properties",
    "scripts/**",
    "crates/**",
    "xtask/**",
    "default_config/**",
    "docs/**",
    "vendor/arboard/**",

    ".gitignore",
    ".node-version",
    "about.hbs",
    "about.toml",
    "Cargo.lock",
    "Cargo.toml",
    "clippy.toml",
    "deny.toml",
    "justfile",
    "README.md",
    "rust-toolchain.toml",
    "rustfmt.toml",
    "tombi.toml",
]
SPDX-FileCopyrightText = "Contributors to Lapiz"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "crates/lapiz_abr/**",
    "crates/lapiz_abr_derive/**",
    "crates/lapiz_lazuli/**",
]
SPDX-FileCopyrightText = "Contributors to Lapiz"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "android/gradle/wrapper/**"
SPDX-FileCopyrightText = "Gradle, Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/iced_winit/**"
SPDX-FileCopyrightText = ["Contributors to iced", "Contributors to Lapiz"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "crates/lapiz_render/src/shaders/hash.wesl"
SPDX-FileCopyrightText = [
    "2014 David Hoskins",
    "Contributors to Lapiz",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "crates/lapiz_render/src/shaders/math.wesl"
SPDX-FileCopyrightText = [
    "2015 Inigo Quilez",
    "Contributors to Lapiz",
]
SPDX-License-Identifier = "GPL-3.0-or-later AND MIT"

[[annotations]]
path = "docs/readme/main.png"
SPDX-FileCopyrightText = [
    "Contributors to Lapiz",
    "Dariusz Duchiewicz",
]
SPDX-License-Identifier = "GPL-3.0-or-later AND LicenseRef-Pexels"
