[package]
name = "lapiz_utils"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bevy_color.workspace = true
downcast-rs.workspace = true
dyn-clone.workspace = true
iced_core.workspace = true
lapiz_utils_derive.workspace = true
tracing.workspace = true

[lints]
workspace = true
