[package]
name = "lapiz_input"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
bitflags.workspace = true
futures.workspace = true
glam.workspace = true
iced_core.workspace = true
indexmap.workspace = true
lapiz_assets.workspace = true
lapiz_runtime.workspace = true
lapiz_utils.workspace = true
log.workspace = true
parse-display.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
toml.workspace = true
