[package]
name = "lapiz_image"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bevy_math.workspace = true
bytemuck.workspace = true
lapiz_color.workspace = true
lapiz_i18n.workspace = true
lapiz_lazuli.workspace = true
lapiz_render.workspace = true
lapiz_runtime.workspace = true
lapiz_shader_graph.workspace = true
lapiz_utils.workspace = true
lapiz_widgets.workspace = true
dashmap.workspace = true
downcast-rs.workspace = true
dyn-clone.workspace = true
encase.workspace = true
flate2.workspace = true
futures.workspace = true
glam.workspace = true
half.workspace = true
image.workspace = true
indexmap.workspace = true
log.workspace = true
moxcms.workspace = true
num_enum.workspace = true
palette.workspace = true
parking_lot.workspace = true
parse-display.workspace = true
rayon.workspace = true
rmp-serde.workspace = true
rust-embed.workspace = true
schemars.workspace = true
serde.workspace = true
uuid.workspace = true
wesl.workspace = true
wgpu.workspace = true

[build-dependencies]
wesl.workspace = true
