[[categories]]
title = "menu_file"
items = [
    "open_file_action",
    "Separator",
    "save_file_action",
]

[[categories]]
title = "menu_edit"
items = [
    "undo_action",
    "redo_action",
    "Separator",
    "paste_into_new_layer_action",
]

[[categories]]
title = "menu_layer"
items = [
    "create_new_layer_action",
    "group_selected_layers_action",
    "Separator",
    "move_layer_up_action",
    "move_layer_down_action",
    "delete_selected_layers_action",
]

[[categories]]
title = "menu_select"
items = [
    "select_previous_layer_action",
    "select_next_layer_action",
    "Separator",
    "delete_selection_action",
]

[[categories]]
title = "menu_filter"
items = [
    "toggle_filter_panel_action",
]

[[categories]]
title = "menu_window"
items = [
    "open_brush_editor_action",
    "toggle_filter_panel_action",
    "Separator",
    { title = "menu_theme_submenu", items = [
        # Injected in runtime
    ] },
    { title = "menu_language_submenu", items = [
        # Injected in runtime
    ] }
]
