[package]
name = "lapiz_image_adapter"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
iced_core.workspace = true
iced_futures.workspace = true
iced_runtime.workspace = true
iced_widget.workspace = true
image.workspace = true
lapiz_canvas.workspace = true
lapiz_config.workspace = true
lapiz_i18n.workspace = true
lapiz_image.workspace = true
lapiz_lazuli.workspace = true
lapiz_render.workspace = true
lapiz_runtime.workspace = true
lapiz_utils.workspace = true
lapiz_widgets.workspace = true
log.workspace = true
parse-display.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
rust-embed.workspace = true
