[package]
name = "lapiz_report"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
gfxinfo.workspace = true
lapiz_dirs.workspace = true
lapiz_runtime.workspace = true
lapiz_utils.workspace = true
log.workspace = true
rand.workspace = true
sysinfo.workspace = true
wgpu.workspace = true

[lints]
workspace = true
