[package]
name = "lapiz_transform_tool"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bevy_math.workspace = true
bitflags.workspace = true
lapiz_canvas.workspace = true
lapiz_math.workspace = true
lapiz_image.workspace = true
lapiz_input.workspace = true
lapiz_render.workspace = true
lapiz_tools.workspace = true
lapiz_runtime.workspace = true
lapiz_undo.workspace = true
lapiz_utils.workspace = true
lapiz_widgets.workspace = true
encase.workspace = true
glam.workspace = true
parse-display.workspace = true
tracing.workspace = true
iced_core.workspace = true
iced_graphics.workspace = true
iced_wgpu.workspace = true
iced_widget.workspace = true
iced_runtime.workspace = true
wgpu.workspace = true
