[package]
name = "lapiz_color"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
lapiz_math.workspace = true
lapiz_runtime.workspace = true
lapiz_utils.workspace = true
glam.workspace = true
moxcms.workspace = true
parse-display.workspace = true
serde.workspace = true
wesl.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_ColorSystem",
] }

[build-dependencies]
wesl.workspace = true

[lints]
workspace = true
