[package]
name = "lapiz_color_selector"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
bytemuck.workspace = true
lapiz_i18n.workspace = true
rust-embed.workspace = true
lapiz_color.workspace = true
lapiz_render.workspace = true
lapiz_runtime.workspace = true
lapiz_widgets.workspace = true
encase.workspace = true
glam.workspace = true
iced_core.workspace = true
iced_runtime.workspace = true
iced_wgpu.workspace = true
iced_widget.workspace = true
moxcms.workspace = true
parse-display.workspace = true
wesl.workspace = true
wgpu.workspace = true

[lints]
workspace = true
