name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  desktop:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - run: just setup-rust

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: workspace-deps
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          cache-on-failure: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - run: just setup-ci

      - uses: tombi-toml/setup-tombi@v1.5.5

      - run: just check

      - run: just test

      - run: just package desktop dev

      - uses: actions/upload-artifact@v7
        with:
          name: build-${{ runner.os }}-${{ runner.arch }}
          retention-days: 1
          if-no-files-found: error
          path: |
            target/package/*.zip
            target/package/*.tar.gz
            target/package/*.sha256
            target/package/*.debug
            target/package/*.pdb

  android:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v7

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"

      - name: Install Android CLI
        shell: bash
        run: curl -fsSL https://dl.google.com/android/cli/latest/linux_x86_64/install.sh | bash

      - run: just setup-android

      - run: just setup-for-check

      - uses: tombi-toml/setup-tombi@v1.5.5

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: workspace-deps-android
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - run: just check android aarch64

      - run: just package android dev aarch64

      - uses: actions/upload-artifact@v7
        with:
          name: build-android-aarch64
          retention-days: 1
          if-no-files-found: error
          path: |
            target/package/*.apk
            target/package/*.so
            target/package/*.sha256
